---
version: 2
jobs:
  build:
    working_directory: ~/geoportal
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
          geoportal_DB_HOST: localhost
          geoportal_DB_USERNAME: geoblacklight
      - image: solr:7.1-alpine
        command: bin/solr -cloud -noprompt -f -p 8985
    steps:
      - checkout
      # Update node
            - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      # Update chrome
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo apt-get update
      - run: sudo apt-get -y install google-chrome-stable
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: geoportal-{{ checksum "Gemfile.lock" }}
      # Load Solr
      - run: dockerize -wait tcp://localhost:8985 -timeout 1m
      - run:
          name: Load config into solr
          command: |
            cd solr/conf
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8985/solr/admin/configs?action=UPLOAD&name=geoportal"
            curl -H 'Content-type: application/json' http://localhost:8985/api/collections/ -d '{create: {name: geoportal-core-test, config: geoportal, numShards: 1}}'
      # Yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Bundle install dependencies
      - run: gem install bundler:2.0.1
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rake geoblacklight:index:seed
      - run: bundle exec rake test
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: geoportal-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
